# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name:  nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # namespace: nginx
  labels:
    apps: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: nginx
  template:
    metadata:
      labels:
        apps: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1000m"
            memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  # namespace: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
      name: http
  selector:
    apps: nginx

