apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwOi8vMTcyLjMwLjAuMjo1MDUwIjp7InVzZXJuYW1lIjoib3NjYXIiLCJwYXNzd29yZCI6Ik5vZFZZeExpNC1wRXlFNlFzYnc3IiwiZW1haWwiOiJvc2NhcjIxN2JAZ21haWwuY29tIiwiYXV0aCI6ImIzTmpZWEk2VG05a1ZsbDRUR2swTFhCRmVVVTJVWE5pZHpjPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: gitlab-onos
  namespace: kube-system
type: kubernetes.io/dockerconfigjson