apiVersion: v1 
kind: Pod 
metadata: 
  name: busybox 
  namespace: busybox 
spec: 
  volumes:
  - name: busybox-data 
    persistentVolumeClaim:
      claimName: busybox-data-pvc
  containers: 
  - name: busybox 
    image: ellerbrock/alpine-bash-curl-ssl 
    command: 
      - sleep 
      - "3600" 
    imagePullPolicy: IfNotPresent 
    volumeMounts:
      - name: busybox-data
        mountPath: /test_files
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker-1 # Edit this to be an actual kubernetes name of your server
  restartPolicy: Always
