apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox
  labels:
    apps: busybox
spec:
  selector:
    matchLabels:
      apps: busybox
  template:
    metadata:
      labels:
        apps: busybox
    spec:
      volumes:
      - name: busybox-data 
        persistentVolumeClaim:
          claimName: busybox-data-pvc
      containers: 
      - name: busybox 
        image: ellerbrock/alpine-bash-curl-ssl 
        command: 
          - sleep 
          - "3600" 
        imagePullPolicy: IfNotPresent 
        volumeMounts:
          - name: busybox-data
            mountPath: /test_files
      tolerations:
        # Make sure sona-node gets scheduled on all nodes.
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
