kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-data-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    # Edit this to be an actual path on your server's filesystem
    path: /home/oscar/curl_test_file
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1 # Edit this to be an actual kubernetes name of your server
          - worker-2 # Edit this to be an actual kubernetes name of your server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-conf-pvc
  namespace: nginx
spec:
  storageClassName: nginx-conf
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    # Edit this to be an actual path on your server's filesystem
    path: /etc/nginx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1 # Edit this to be an actual kubernetes name of your server
          - worker-2 # Edit this to be an actual kubernetes name of your server
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-default-pvc
  namespace: nginx
spec:
  storageClassName: nginx-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-default
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    # Edit this to be an actual path on your server's filesystem
    path: /etc/nginx/sites-enabled
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1 # Edit this to be an actual kubernetes name of your server
          - worker-2 # Edit this to be an actual kubernetes name of your server