kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iperf-data-pvc
  # namespace: iperf
spec:
  storageClassName: testfile-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iperf-data
  # namespace: iperf
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: testfile-local-storage
  local:
    # Edit this to be an actual path on your server's filesystem
    path: /home/oscar/test_files
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-1 # Edit this to be an actual kubernetes name of your server
          - worker-2 # Edit this to be an actual kubernetes name of your server