apiVersion: v1 
kind: Pod 
metadata: 
  name: iperf-client 
  # namespace: iperf 
spec: 
  volumes:
  - name: iperf-data 
    persistentVolumeClaim:
      claimName: iperf-data-pvc
  containers: 
  - name: client
    image: networkstatic/iperf3
    command: ['/bin/sh', '-c', 'sleep infinity']
    imagePullPolicy: IfNotPresent 
    volumeMounts:
      - name: iperf-data
        mountPath: /test_files
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker-1 # Worker runs iperf client
  restartPolicy: Always
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: iperf-server 
  # namespace: iperf 
spec: 
  containers: 
  - name: server 
    image: networkstatic/iperf3
    args: ['-s']
    ports:
    - containerPort: 5201
      name: server
    imagePullPolicy: IfNotPresent 
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker-2 # Worker 2 is the iperf server side
  restartPolicy: Always
